package com.collab.platform.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;

@Entity
@Table(name = "board_items", indexes = {
    @Index(name = "idx_board_room", columnList = "roomId")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class BoardItem {

    @Id
    @Column(nullable = false, length = 64)
    private String id;

    @Column(nullable = false, length = 64)
    private String roomId;

    @Column(nullable = false, length = 200)
    private String title;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private ItemStatus status;

    @Column(length = 30)
    private String color;

    /**
     * Monotonically increasing version counter used for Last-Write-Wins and optimistic concurrency tracking.
     */
    @Column(nullable = false)
    private Long version;

    /**
     * Epoch milliseconds timestamp sent by the client when edit was submitted.
     */
    @Column(nullable = false)
    private Long clientTimestamp;

    /**
     * Epoch milliseconds timestamp generated by the server when edit was accepted.
     */
    @Column(nullable = false)
    private Long serverTimestamp;

    @Column(nullable = false, length = 80)
    private String lastModifiedBy;

    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    @Column(nullable = false)
    private Instant updatedAt;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = Instant.now();
        }
        updatedAt = Instant.now();
        if (version == null) {
            version = 1L;
        }
        if (serverTimestamp == null) {
            serverTimestamp = System.currentTimeMillis();
        }
        if (clientTimestamp == null) {
            clientTimestamp = serverTimestamp;
        }
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = Instant.now();
        serverTimestamp = System.currentTimeMillis();
    }
}
